hurmit: &hurmit Hurmit Nerd Font:pixelsize=12
hurmit_small: &hurmit_small Hurmit Nerd Font:pixelsize=9
hurmit_large: &hurmit_large Hurmit Nerd Font:pixelsize=15

bar:
  height: 30
  location: "top"
  #monitor: ""
  layer: "bottom"
  border:
    width: 0
    color: 121212dd
  spacing: 0
  margin: 0
  background: 121212dd
  foreground: dbdbdbff
  font: *hurmit

  left:
  - river:
      all-monitors: true
      anchors:
      - base: &river_anchor
          left-margin: 10
          right-margin: 13 
          default: {string: {text: "#"}}
          conditions:
            id == 1: {string: {text: "1"}}
            id == 2: {string: {text: "2"}}
            id == 3: {string: {text: "3"}}
            id == 4: {string: {text: "4"}}
            id == 5: {string: {text: "5"}}
            id == 6: {string: {text: "6"}}
            id == 7: {string: {text: "7"}}
            id == 8: {string: {text: "8"}}
            id == 9: {string: {text: "9"}}

      content:
        map:
          on-click: 
            left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
            right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
            middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
          conditions:
            state == urgent:
              map:
                <<: *river_anchor
                deco:
                  stack:
                  - background:
                      color: b7472a22
                  - underline:
                      size: 4
                      color: b7472aff
            id > 9: {empty: {}}
            state == focused:
              map:
                <<: *river_anchor
                deco:
                  stack:
                  - background:
                      color: 42781922
                  - underline:
                      size: 4
                      color: 427819ff
            occupied:
              map:
                <<: *river_anchor
                deco:
                  stack:
                  - background:
                      color: 586e7522
                  - underline:
                      size: 4
                      color: 586e75ff
            ~occupied:
              map:
                <<: *river_anchor
                deco:
                  stack:
                  - underline:
                      size: 4
                      color: 586e75ff

  - label:
      content:
        string:
          text: " "

  - foreign-toplevel:
      content:
        map:
          conditions:
            ~activated: {empty: {}}
            activated:
              - string: {text: "{app-id}", foreground: ffa0a0ff}
              - string: {text: ": {title}"}

  #center:
  #- mpd:
  #    host: /run/mpd/socket
  #    anchors:
  #      list: &artist_album_title
  #        spacing: 0
  #        items:
  #          - map:
  #              conditions:
  #                state == playing: {string: {text: "{artist}"}}
  #                state == paused: {string: {text: "{artist}", foreground: ffffff66}}
  #          - string: {text: " | ", foreground: ffffff66}
  #          - map:
  #              conditions:
  #                state == playing: {string: {text: "{album}"}}
  #                state == paused: {string: {text: "{album}", foreground: ffffff66}}
  #          - string: {text: " | ", foreground: ffffff66}
  #          - map:
  #              conditions:
  #                state == playing: {string: {text: "{title}", foreground: ffa0a0ff}}
  #                state == paused: {string: {text: "{title}", foreground: ffffff66}}

  #    content:
  #      map:
  #        margin: 10
  #        conditions:
  #          state == offline: {string: {text: offline, foreground: ff0000ff}}
  #          state == stopped: {string: {text: stopped}}
  #          state == paused: {list: *artist_album_title}
  #          state == playing: {list: *artist_album_title}

  right:
  #- pulse:
  #    content:
  #      string: {text: "{sink_percent}% ({sink_port})"}
  #      map:
  #        on-click:
  #          left: /bin/sh -c "pavucontrol"
  #          right: /bin/sh -c "pactl -- set-sink-mute @DEFAULT_SINK@ toggle"
  #        conditions:
  #          sink_muted: {string: {text: , foreground: ffffff66}}
  #          ~sink_muted:
  #            ramp:
  #              tag: percent
  #              items:
  #              - string: {text: ""}
  #              - string: {text: ""}
  #              - string: {text: ""}
  #        conditions:
  #          ~sink_online: {string: {text: "", foreground: 586e75ff}}
  #          sink_online:
  #- alsa:
  #    card: hw:C1D0
  #    mixer: Master
  #    content:
  #      map:
  #        on-click:
  #          left: foot -a "popup" -- alsamixer
  #          right: /bin/sh -c "pactl -- set-sink-mute @DEFAULT_SINK@ toggle"
  #        font: *hurmit_large
  #        conditions:
  #          ~online:
  #          - string: {text: "󰖁"}
  #          muted:
  #          - string: {text: "󰝟"}
  #          ~muted:
  #          - ramp:
  #              tag: percent
  #              items:
  #                - string: {text: "󰕿"}
  #                - string: {text: "󰖀"}
  #                - string: {text: "󰕾"}
  #          - string: {text: " {percent}%"}

  - network:
      name: eth0
      poll-interval: 500
      content:
      - string: {text: "󰈀 "}
      - string: {text: "{dl-speed:kb}", foreground: 00ff00ff}
      - string: {text: "/"}
      - string: {text: "{ul-speed:kb}", foreground: 0000ffff}
      - string: {text: " Kb/s"}

  - label:
      content:
        string:
          text: " | "

  - network:
      name: wlan0
      poll-interval: 500
      content:
      - string: {text: " "}
      - string: {text: "{dl-speed:kb}", foreground: 00ff00ff}
      - string: {text: "/"}
      - string: {text: "{ul-speed:kb}", foreground: 0000ffff}
      - string: {text: " Kb/s"}

  - label:
      content:
        string:
          text: " | "

  - xkb:
      content:
        string:
          on-click:
          text: "󰌌 {symbol}"

  - label:
      content:
        string:
          text: " | "

  - label:
      content:
        string:
          on-click:
            left: foot -a "popup" -- alsamixer
            right: /bin/sh -c "pactl -- set-sink-mute @DEFAULT_SINK@ toggle"
          text: "󰕾"

  - label:
      content:
        string:
          text: " | "

  - backlight:
      name: amdgpu_bl1
      content:
      - string: {text: "󰃟"}
      - string: {text: " {percent}%"}

  - label:
      content:
        string:
          text: " | "

  - battery:
      name: BAT0
      poll-interval: 60000
      anchors:
        discharging: &discharging
          list:
            items:
            - ramp:
                tag: capacity
                items:
                - string: {text: "󱃍", foreground: b7472aff}
                - string: {text: "󰁺", foreground: b7472aff}
                - string: {text: "󰁻", foreground: ffcf00ff}
                - string: {text: "󰁼"}
                - string: {text: "󰁽"}
                - string: {text: "󰁾"}
                - string: {text: "󰁿"}
                - string: {text: "󰂁"}
                - string: {text: "󰂂"}
                - string: {text: "󰁹"}
            - string: {text: " {capacity}%"}
      content:
        map:
          conditions:
            state == unknown:
              <<: *discharging
            state == discharging:
              <<: *discharging
            state == "not charging":
              <<: *discharging
            state == charging:
            - ramp:
                tag: capacity
                items:
                  - string: {text: "󰢟", foreground: 427819ff}
                  - string: {text: "󰢜", foreground: 427819ff}
                  - string: {text: "󰂆", foreground: 427819ff}
                  - string: {text: "󰂇", foreground: 427819ff}
                  - string: {text: "󰂈", foreground: 427819ff}
                  - string: {text: "󰢝", foreground: 427819ff}
                  - string: {text: "󰂉", foreground: 427819ff}
                  - string: {text: "󰢞", foreground: 427819ff}
                  - string: {text: "󰂊", foreground: 427819ff}
                  - string: {text: "󰂋", foreground: 427819ff}
            - string: {text: " {capacity}%", foreground: 427819ff}
            state == full:
            - string: {text: "󰂅", foreground: 427819ff}
            - string: {text: " {capacity}%", foreground: 427819ff}

  - label:
      content:
        string:
          text: " | "

  - clock:
      date-format: "%Y/%m/%d"
      time-format: "%H:%M"
      content:
      - string: {text: "{time} {date}"}

  - label:
      content:
        string:
          text: " "
